---
- name: Finalize Server2 Configuration
  hosts: server2
  become: true

  tasks:
    - name: Install required packages
      dnf:
        name:
          - chrony
          - cockpit
          - cockpit-system
        state: present

    - name: Configure NTP server
      replace:
        path: /etc/chrony/chrony.conf
        regexp: '^pool.*$'
        replace: 'pool 3.north-america.pool.ntp.org iburst'

    - name: Start and enable chronyd
      service:
        name: chronyd
        state: restarted
        enabled: yes

    - name: Start and enable Cockpit
      service:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: Create cron job script
      copy:
        dest: /usr/local/bin/check_cockpit.sh
        mode: '0755'
        content: |
          #!/bin/bash
          systemctl is-active --quiet cockpit.socket
          if [ $? -eq 0 ]; then
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Cockpit service is running" >> /var/log/automation.log
          else
              echo "$(date '+%Y-%m-%d %H:%M:%S') - Cockpit service is not running" >> /var/log/automation.log
          fi

    - name: Create automation.log file
      file:
        path: /var/log/automation.log
        state: touch
        mode: '0644'

    - name: Setup cron job
      cron:
        name: "runningaway"
        minute: "*/5"
        job: "/usr/local/bin/check_cockpit.sh"
        state: present