---
- name: Setup team folders on Server2
  hosts: server2
  become: true

  tasks:
    - name: Create volume group
      lvg:
        vg: itvg
        pvs: /dev/nvme1n1
        state: present

    - name: Create logical volume
      lvol:
        vg: itvg
        lv: itlv
        size: 1g
        state: present

    - name: Create XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/itvg/itlv

    - name: Create mount point directory
      file:
        path: /extdrive
        state: directory
        owner: root
        group: IT
        mode: '2770'

    - name: Add mount to /etc/fstab
      mount:
        path: /extdrive
        src: /dev/itvg/itlv
        fstype: xfs
        state: mounted
        opts: defaults
        
    - name: Set permissions on mounted directory
      file:
        path: /extdrive
        state: directory
        owner: root
        group: IT
        mode: '2770'
        recurse: yes